"""empty message

Revision ID: 4a13d89d7754
Revises: 
Create Date: 2025-07-28 17:52:48.657749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a13d89d7754'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display',
    sa.Column('DisplayID', sa.Integer(), nullable=False),
    sa.Column('CurrentAmount', sa.Integer(), nullable=False),
    sa.Column('RemainingAmount', sa.Integer(), nullable=False),
    sa.Column('RemainingWorkTime', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('DisplayID')
    )
    op.create_table('hourly_wage',
    sa.Column('HourlyWageID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NormalTimeWage', sa.Integer(), nullable=False),
    sa.Column('NightTimeWage', sa.Integer(), nullable=False),
    sa.Column('MidnightTimeWage', sa.Integer(), nullable=False),
    sa.Column('NormalStart', sa.Float(), nullable=False),
    sa.Column('NormalEnd', sa.Float(), nullable=False),
    sa.Column('NightStart', sa.Float(), nullable=False),
    sa.Column('NightEnd', sa.Float(), nullable=False),
    sa.Column('MidnightStart', sa.Float(), nullable=False),
    sa.Column('MidnightEnd', sa.Float(), nullable=False),
    sa.Column('DayType', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('HourlyWageID')
    )
    op.create_table('setting',
    sa.Column('SettingID', sa.Integer(), nullable=False),
    sa.Column('GoalAmount', sa.Integer(), nullable=False),
    sa.Column('AchievementDay', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('SettingID')
    )
    op.create_table('shift',
    sa.Column('ShiftID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ShiftDay', sa.Date(), nullable=False),
    sa.Column('StartTime', sa.Float(), nullable=False),
    sa.Column('EndTime', sa.Float(), nullable=False),
    sa.Column('BreakStartTime', sa.Float(), nullable=False),
    sa.Column('BreakeEndTime', sa.Float(), nullable=False),
    sa.Column('DayType', sa.Integer(), nullable=False),
    sa.Column('Complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['DayType'], ['hourly_wage.DayType'], ),
    sa.PrimaryKeyConstraint('ShiftID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift')
    op.drop_table('setting')
    op.drop_table('hourly_wage')
    op.drop_table('display')
    # ### end Alembic commands ###
