"""add HourlyWage with DayType

Revision ID: bf0676b7c6c9
Revises: 
Create Date: 2025-07-24 14:44:00.414754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0676b7c6c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly_wage',
    sa.Column('HourlyWageID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NormalTimeWage', sa.Integer(), nullable=False),
    sa.Column('NightTimeWage', sa.Integer(), nullable=False),
    sa.Column('MidnightTimeWage', sa.Integer(), nullable=False),
    sa.Column('DayType', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('HourlyWageID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hourly_wage')
    # ### end Alembic commands ###
